### ISSUE TITLE
FYI there are a lot of components that do this already

### ISSUE THREAD

**Issue by gajus** [mapbox/react-simple-surveyor#1]
* https://www.npmjs.com/package/react-container-dimensions
* https://github.com/joeybaker/react-element-query
* https://github.com/FezVrasta/react-element-queries

see also https://github.com/FezVrasta/react-element-queries/issues/1

**Comment by davidtheclark** [comment]
Thanks @gajus. In the README I've noted these and other similar modules. The goal here is to be small and simple and focused, more so than the other available modules. The closest I've found to what I'm looking for is https://github.com/trotzig/react-with-available-width, and I've opened an issue over there about possibly merging this work: https://github.com/trotzig/react-with-available-width/issues/4

**Comment by gajus** [comment]
From the little digging that I've done, https://github.com/wnr/element-resize-detector is by far the most efficient implementation. The bundle size comes from graceful degradation for legacy browsers. There is still quite a few things that could be improved, starting with multiple modules per distribution allowing to drop older browsers.
